version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: my-backend-image:latest  # Nome immagine per il backend
    ports:
      - "5000:5000"  # Esponi la porta 5000 del backend
    networks:
      - chatbot-network # Rete personalizzata

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    image: my-frontend-image:latest  # Nome immagine per il frontend
    ports:
      - "3000:3000"  # Esponi la porta 3000 per il frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000  # Connessione al backend tramite nome del servizio
    networks:
      - chatbot-network # Rete personalizzata

networks:
  chatbot-network:  # Rete personalizzata
    driver: bridge # Driver bridge per la rete di default
